### ISSUE TITLE
HTTPS is broken in Firefox

### ISSUE THREAD

**Issue by dmakaroff** [justcoding121/Titanium-Web-Proxy#180]
Even when **[security.enterprise_roots.enabled](https://wiki.mozilla.org/CA:AddRootToFirefox)** is set to **true** Firefox still complains about insecure connection.

**Comment by dmakaroff** [comment]
Works with Fiddler 4 without manually importing its certificate.

**Comment by rvknth043** [comment]
have we found any solution to overcome this problem..

**Comment by judebigj** [comment]
I am facing the same problem with chrome and firefox. It works fine with IE.
Has anyboby found solution to this?

**Comment by justcoding121** [comment]
As per below guideline, firefox should use system certificates if added to Local Machine Store. I modified the code so that it will be added by default (when proxy is running with admin rights).

https://wiki.mozilla.org/CA:AddRootToFirefox

But still it seems firefox is not picking it up.

**Comment by justcoding121** [comment]
@dmakaroff We have a solution if you are okay with Bouncy Castle under latest Beta. #199 has more details.

`proxyServer.CertificateEngine = Network.CertificateEngine.BouncyCastle;`

**Comment by justcoding121** [comment]
Fixed windows certificate maker as well to support alternative names. So this should be resolved.

**Comment by honfika** [comment]
I still have issues with Firefox.
Edge and Chrome works.
Both with DefaultWindows a BC cert provider. (I'm also deleting the rootCert.pfx file when switching between them)
I tried the latest revision and the revision after "#199 Fix subject alt names for Bouncy Castle" commit. Both from developer branch. Both fails on Firefox.

Firefox (53.0.2, 64bit) shows:
Your connection is not secure

The owner of hup.hu has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.

This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.

Advanced:
hup.hu uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. Error code: SEC_ERROR_UNKNOWN_ISSUER

What am I doing wrong?

**Comment by honfika** [comment]
I forget to mention that security.enterprise_roots.enabled is set to true.

**Comment by honfika** [comment]
Sorry, solved. 
Deleted every Titanium certificate from Local Machine and User stores, rootCert.pfx,
Started the proxy again.
Restarted firefox. (Probably this step solved the problem, it seems that FF is caching the certificates, even it was not found)
