### ISSUE TITLE
Having trouble with Dropbox App

### ISSUE THREAD

**Issue by judebigj** [justcoding121/Titanium-Web-Proxy#204]
Hello,
        I have added the dropbox.com url in ExcludedHttpsHostNameRegex, knowning that it uses certificate pinning. Inspite of this, my dropbox app, which is installed on my windows 10 machine, is not able to sync. It keeps saying "can't establish secure internet connection".
Can you please help me understand, why this could be happening.

**Comment by justcoding121** [comment]
Can you debug and find the hostname dropbox is trying to connect. May be its connecting to another hostname. 

Error will be throw at [this line](https://github.com/justcoding121/Titanium-Web-Proxy/blob/develop/Titanium.Web.Proxy/RequestHandler.cs#L123), and at that point you can inspect hostname dropbox is trying to connect to,

**Comment by justcoding121** [comment]
This was a bug in code, thanks for reporting.

Should be fixed in latest develop now

**Comment by judebigj** [comment]
Thanks for your attention towards this issue. By when can we expect the fix?

**Comment by judebigj** [comment]
I tried the fix you suggested, ie send httpcmd as null, but still facing the same issue. I am not able to sync the file in dropbox app. The host ends with dropbox.com (which i have added in exclude list). and the port is 443. I tried making isHttps to true depending on the port number without success.
Any suggestions?

**Comment by justcoding121** [comment]
I have dropbox and it is syncing fine. It was not syncing before the fix. Are you on latest develop?

**Comment by judebigj** [comment]
Have tried syncing a file?

**Comment by judebigj** [comment]
My bad, I had commented a line of code.That was causing the problem. Its working now.
Thanks for your help
