### ISSUE TITLE
Modify request problem

### ISSUE THREAD

**Issue by ljh1991125** [justcoding121/Titanium-Web-Proxy#543]
I am using titanium proxy as reverse proxy in my project.
When I change request uri at BeforeRequest function, at HTTP it works but HTTPS it do not work.
What's problem
Here is my code.

```
proxyServer.BeforeRequest += OnRequest;

public async Task OnRequest(object sender, SessionEventArgs e)
{
             if (e.WebSession.Request.RequestUri.Host == "www.aaa.com")
             {                 
                 e.WebSession.Request.RequestUri = new Uri("https://www.bing.com");
             }
 
             if (e.WebSession.Request.HasBody)
             {
                   var bodyBytes = await e.GetRequestBody();
                   e.SetRequestBody(bodyBytes);
              }
}
```

At web browser, when i input http://www.aaa.com, it successfully connect to www.bing.com but when i input https://www.aaa.com, it fail.

**Comment by ljh1991125** [comment]
I found same problem at here [https://stackoverflow.com/questions/54177485/firewall-causes-titanium-web-proxy-to-fail-to-change-request-url](url).
Is it ssl clienthello problem?

**Comment by justcoding121** [comment]
Are you sure your code matches the hostname in `e.WebSession.Request.RequestUri.Host` exactly as it appears? Sometimes you won't find the www. prefix.

**Comment by justcoding121** [comment]
If one of the request headers also have a hostname header, you would need to modify that as well to be safe.

**Comment by ljh1991125** [comment]
I also tried to change hostname header but it does not work.

**Comment by justcoding121** [comment]
Good find.  I was able to reproduce the issue with integration tests.
https://github.com/justcoding121/Titanium-Web-Proxy/blob/master/tests/Titanium.Web.Proxy.IntegrationTests/ReverseProxyTests.cs

This was fixed in the latest beta nuget package release. (Titanium.Web.Proxy.3.0.892-beta) Reopen if still not fixed.

**Comment by ljh1991125** [comment]
Thank you for you help.
I update to Titanium Proxy 3.0.895 but it still does not work.
I am using ExplicitProxyEndPoint not TransparentProxyEndPoint.
I think when proxy tries to connect **unconnectable** ssl server, problem occurs.
There is no problem when connecting vaild ssl servers.
Here is my source code.

<pre>
...
proxyServer.BeforeRequest += OnRequest;
proxyServer.BeforeResponse += OnResponse;
proxyServer.ServerCertificateValidationCallback += OnCertificateValidation;
proxyServer.ClientCertificateSelectionCallback += OnCertificateSelection;

explicitEndPoint = new ExplicitProxyEndPoint(IPAddress.Any, 8000, true)
{
         //Use self-issued generic certificate on all https requests
         //Optimizes performance by not creating a certificate for each https-enabled domain
         //Useful when certificate trust is not required by proxy clients
         //GenericCertificate = new  X509Certificate2(Path.Combine(System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "rootCert.pfx"), "")
};

//Fired when a CONNECT request is received
explicitEndPoint.BeforeTunnelConnectRequest += OnBeforeTunnelConnectRequest;
...
public async Task OnRequest(object sender, SessionEventArgs e)
{
       if (e.HttpClient.Request.RequestUri.Host == "www.aaa.com")
       {
                e.HttpClient.Request.RequestUri = new Uri("https://www.bing.com/");
                e.HttpClient.Request.Host = "www.bing.com";
       }
}
...
</pre>

**Comment by lightfiretw** [comment]
> Thank you for you help.
> I update to Titanium Proxy 3.0.895 but it still does not work.
> I am using ExplicitProxyEndPoint not TransparentProxyEndPoint.
> I think when proxy tries to connect **unconnectable** ssl server, problem occurs.
> There is no problem when connecting vaild ssl servers.

Yeah, I was the one asking the question on stackoverflow.
Got the solution by basically doing the same thing from Transparent to Explicit.
remove these
```
Task<TcpServerConnection> prefetchConnectionTask = null;
bool closeServerConnection = false;
bool calledRequestHandler = false;
```
and it should work, but got no idea what is the consequence of doing so.
