### ISSUE TITLE
Negative Number being Passed to System.IO.BinaryReader.ReadBytes(int count) by e.GetResponseBodyAsString()

### ISSUE THREAD

**Issue by clindsb1** [justcoding121/Titanium-Web-Proxy#71]
According to the Stack Trace and error message, a negative number is being passed to System.IO.BinaryReader.ReadBytes for the count Parameter. Only zero and non-negative numbers are valid. This in in 2.1.110 with .Net Framework 4.5.

![image](https://cloud.githubusercontent.com/assets/14785545/15367478/395d6102-1cf7-11e6-99de-7be79c49202e.png)

![image](https://cloud.githubusercontent.com/assets/14785545/15367560/b20867aa-1cf7-11e6-94ff-c0495e05361e.png)

![image](https://cloud.githubusercontent.com/assets/14785545/15367581/c22990aa-1cf7-11e6-995f-ece89a7a1ec0.png)

**Comment by justcoding121** [comment]
I think this should be fixed in latest beta release

[Nuget link for beta](https://www.nuget.org/packages/Titanium.Web.Proxy/2.1.111-beta)

If not please reopen and I would like to see an example to reproduce this issue.

**Comment by clindsb1** [comment]
There is still an issue but it has changed slightly now.
![image](https://cloud.githubusercontent.com/assets/14785545/15437598/fe470f8c-1e95-11e6-8680-593eb7ca563d.png)

**Comment by clindsb1** [comment]
I don't seem to have the ability to reopen the issue.

**Comment by justcoding121** [comment]
Can you please provide an example

**Comment by clindsb1** [comment]
The communications are using soap envelopes. I am passing a request through the proxy and when a response is received, I get that error. The response is not forwarded to the host that made the request. I also tried making my OnReturn function just return without doing anything and the response is still not forwarded to the host that made the request. What sort of additional information can I give you that would help?

**Comment by clindsb1** [comment]
If I use Wireshark to watch the interface, I can see the request come in to the proxy. The proxy makes some changes to the request and sends it to it's destination. The proxy receives the response back but then the response is not forwarded, even if I don't try to read it at the OnResponse function. When I do try to read it using GetResponseBodyAsString(), I get that error.

**Comment by justcoding121** [comment]
Can your tell me how your content-header looks like?
The stack trace says it cannot parse that header and find the character encoding

**Comment by clindsb1** [comment]
Below is the response HTTP header as captured by WireShark for a message that causes the error:

```
Hypertext Transfer Protocol
    HTTP/1.1 500 Internal Server Error\r\n
    Content-Type: text/xml\r\n
    Server: Microsoft-IIS/7.5\r\n
    X-WIPP-Version: dotnet / 1.4 / SEC-NAE553_1944\r\n
    X-WIPP-RequestID: 999dc017-40ed-46e8-b534-0d47469bee87\r\n
    X-WIPP-Update: Application\r\n
    X-Powered-By: ASP.NET\r\n
    Date: Tue, 24 May 2016 17:17:23 GMT\r\n
    Content-Length: 688\r\n
        [Content length: 688]
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.021920000 seconds]
    [Request in frame: 2916]
```

I don't see a header for character encoding in this response but the proxy doesn't get an error on some other messages with a header like this:

```
Hypertext Transfer Protocol
    HTTP/1.1 500 Internal Server Error\r\n
    Content-Type: text/xml\r\n
    Server: Microsoft-IIS/7.5\r\n
    X-WIPP-Version: dotnet / 1.4 / SEC-NAE553_1944\r\n
    X-WIPP-RequestID: a2c76c77-6559-4c98-a791-09de61c35282\r\n
    X-WIPP-Update: Application\r\n
    X-Powered-By: ASP.NET\r\n
    Date: Tue, 24 May 2016 17:17:23 GMT\r\n
    Content-Length: 688\r\n
        [Content length: 688]
    \r\n
    [HTTP response 1/2]
    [Time since request: 0.017614000 seconds]
    [Request in frame: 2770]
    [Next request in frame: 2888]
    [Next response in frame: 2904]
```

I don't see explicit character encoding in either header.

**Comment by clindsb1** [comment]
Also, I just noticed that when the error occurred, I received an exception event in Visual Studio (I was debugging). The exception was:

'System.IO.IOException'  in System.dll ("Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.")

Maybe that helps?

**Comment by justcoding121** [comment]
I see in stack trace a method call GetResponseEncoding(Response response), which is not a part of beta release. I suspect you are not on latest release.

**Comment by justcoding121** [comment]
Closing this. Not reported again for long time.
